spring.datasource.url=jdbc:postgresql://db.ekdzdczxpwoiqnpphqpu.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=ospital.@19#

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}
